packages:
  - apps/*
  - packages/*

catalogs:
  dev:
    '@antfu/eslint-config': ^6.0.0
    '@commitlint/cli': ^20.1.0
    '@commitlint/config-conventional': ^20.0.0
    '@iconify-json/lucide': ^1.2.70
    '@iconify-json/simple-icons': ^1.2.55
    '@iconify/vue': ^5.0.0
    '@nuxt/devtools': ^2.6.5
    '@nuxtjs/i18n': ^10.1.1
    bumpp: ^10.3.1
    dotenv: ^17.2.3
    drizzle-kit: ^0.31.5
    eslint: ^9.38.0
    husky: ^9.1.7
    lint-staged: ^16.2.6
    nuxt: ^4.1.3
    nuxt-auth-utils: ^0.5.25
    typescript: ^5.9.3
    unbuild: ^3.6.1
    vite: ^7.1.12
    vue-tsc: ^3.1.1
  integrations:
    '@chatgame/stream-journey': ^0.1.6
    '@donation-alerts/api': ^4.0.0
    '@donation-alerts/auth': ^4.0.0
    '@donation-alerts/events': ^4.0.0
    '@neoconfetti/vue': ^2.2.1
    '@number-flow/vue': ^0.4.8
    '@nuxt/ui': ^4.0.1
    '@paralleldrive/cuid2': 2.2.2
    '@telegram-apps/init-data-node': ^1.2.2
    '@telegram-apps/sdk-vue': ^1.0.15
    '@twurple/api': ^7.4.0
    '@twurple/auth': ^7.4.0
    '@twurple/chat': ^7.4.0
    '@twurple/easy-bot': ^7.4.0
    '@twurple/eventsub-ws': ^7.4.0
    '@vueuse/components': ^13.9.0
    '@vueuse/core': ^13.9.0
    '@vueuse/nuxt': ^13.9.0
    drizzle-cuid2: ^2.1.0
    drizzle-orm: ^0.44.6
    grammy: ^1.38.3
    pg: ^8.16.3
    zod: ^4.1.12
  test:
    '@vitest/browser': ^4.0.1
    '@vitest/coverage-v8': ^4.0.1
    playwright: ^1.56.1
    vitest: ^4.0.1
    vitest-browser-vue: ^2.0.0
  types:
    '@types/node': ^24.9.1
    '@types/pg': ^8.15.5

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - msw
  - vue-demi

onlyBuiltDependencies:
  - sharp
  - protobufjs

supportedArchitectures:
  cpu: [x64, arm64]
  os: [linux, darwin, win32]

autoInstallPeers: true
shamefullyHoist: true
