packages:
  - apps/*
  - packages/*
catalog:
  '@antfu/eslint-config': ^5.4.1
  '@chatgame/stream-journey': ^0.0.1
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@d-fischer/typed-event-emitter': ^3.3.3
  '@donation-alerts/api': ^4.0.0
  '@donation-alerts/auth': ^4.0.0
  '@donation-alerts/events': ^4.0.0
  '@iconify-json/lucide': ^1.2.69
  '@iconify-json/simple-icons': ^1.2.54
  '@iconify/vue': ^5.0.0
  '@neoconfetti/vue': ^2.2.1
  '@number-flow/vue': ^0.4.8
  '@nuxt/devtools': ^2.6.5
  '@nuxt/ui': ^3.3.6
  '@nuxtjs/i18n': ^10.1.0
  '@paralleldrive/cuid2': ^2.2.2
  '@prisma/client': ^6.17.1
  '@tailwindcss/vite': ^4.1.14
  '@telegram-apps/init-data-node': ^1.2.2
  '@telegram-apps/sdk-vue': ^1.0.15
  '@tsconfig/node22': ^22.0.2
  '@tsparticles/engine': ^3.9.1
  '@tsparticles/slim': ^3.9.1
  '@tsparticles/vue3': ^3.0.1
  '@twurple/api': ^7.4.0
  '@twurple/auth': ^7.4.0
  '@twurple/chat': ^7.4.0
  '@twurple/easy-bot': ^7.4.0
  '@twurple/eventsub-ws': ^7.4.0
  '@types/howler': ^2.2.12
  '@types/node': ^24.7.2
  '@vitejs/plugin-vue': ^6.0.1
  '@vitest/browser': ^3.2.4
  '@vitest/coverage-v8': ^3.2.4
  '@vue/tsconfig': ^0.8.1
  '@vueuse/components': ^13.9.0
  '@vueuse/core': ^13.9.0
  '@vueuse/nuxt': ^13.9.0
  bumpp: ^10.3.1
  eruda: ^3.4.3
  eslint: ^9.37.0
  grammy: ^1.38.3
  howler: ^2.2.4
  husky: ^9.1.7
  ioredis: ^5.8.1
  lint-staged: ^16.2.4
  nuxt: ^4.0.3
  nuxt-auth-utils: ^0.5.25
  pixi.js: ^8.14.0
  playwright: ^1.56.0
  prisma: ^6.17.1
  tailwindcss: ^4.1.14
  typescript: ^5.9.3
  unbuild: ^3.6.1
  unplugin-auto-import: ^20.2.0
  unplugin-icons: ^22.4.2
  unplugin-vue-components: ^29.1.0
  vite: ^7.1.2
  vite-plugin-terminal: ^1.3.0
  vite-plugin-vue-devtools: ^8.0.2
  vitest: ^3.2.4
  vitest-browser-vue: ^1.1.0
  vue: ^3.5.22
  vue-i18n: ^11.1.12
  vue-router: ^4.5.1
  vue-tsc: ^3.1.1
  zod: ^4.1.12
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - msw
  - vue-demi
onlyBuiltDependencies:
  - sharp
  - protobufjs
supportedArchitectures:
  cpu: [x64, arm64]
  os: [linux, darwin, win32]

autoInstallPeers: true
shamefullyHoist: true
